import styles from "@/styles/Home.module.css";
import Head from "next/head";

import Banner from "@/Componentes/Banner";


export default function Home() {
  return (
    <>
      <Head>
        <title>LinkBio Neymar Jr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Ysabeau+Infant&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet" />
      </Head>

      <main className={`${styles.main}`}>

        <Banner />

      </main>

    </>
  );
}
